### ISSUE TITLE
Crash on 1.20.1 

### ISSUE THREAD

**Issue by sternschnaube** [Fruitloopins/Tabby#5]
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_355 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_329.<init>(class_329.java:144)
	at net.minecraft.class_310.<init>(class_310.java:603)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:75)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 10 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyCount(J)J in tabby.mixins.json:TabSizeMixin from mod tabby failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap tabby-1.20.1-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 14 more

**Comment by GalaxyGaming2000** [comment]
is it possible for the full log?

**Comment by venaminecraft** [comment]
I will send later the full log 😊

**Comment by GalaxyGaming2000** [comment]
> I will send later the full log 😊

alright

**Comment by venaminecraft** [comment]
I was spotting it, it's incompatible with: https://modrinth.com/mod/full-tablist
@ModifyConstant conflict. Skipping tabby.mixins.json:TabSizeMixin from mod tabby->@ModifyConstant::modifyCount(J)J with priority 1000, already redirected by full-tablist.mixins.json:PlayerListHudMixin from mod full-tablist->@ModifyConstant::modifyCount(J)J with priority 1000

**Comment by fungoza** [comment]
incompatible with meteor client (BetterTab module)
same error
will be nice if you add this mods to fabric.mod.json like incompatible
